# Generated by Django 3.2.12 on 2022-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descrpcion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='temporada',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
