# Generated by Django 3.2.12 on 2022-03-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220306_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
